module.exports = {
  Quote: require("./Quote"),
  Venue: require("./Venue"),
  Picture: require("./Picture"),
  Room: require("./Room"),
  User: require("./User"),
  Video: require("./Video"),
  Comment: require("./Comment"),
  City: require("./City"),
  Post: require("./Post"),
  Like: require("./Like"),
  Connection: require("./Connection"),
  Notification: require("./Notification"),
  Popularity: require("./Popularity"),
};
